/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Jump.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Jump(props: any) {
  const group = useRef()
  const { nodes, materials, animations }: any = useGLTF('/Anims3D/SkateAnimsV2.glb')
  const { actions }: any = useAnimations(animations, group)

  const startAnim = () => {
    if (!actions) return
    actions.Jump.play()
  }

  useEffect(() => {
    console.log(props?.playAnim)
  }, [props?.playAnim])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature' rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig1Hips} />
          <skinnedMesh
            name='Ch36'
            geometry={nodes.Ch36.geometry}
            material={materials.Ch36_Body}
            skeleton={nodes.Ch36.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Anims3D/SkateAnimsV2.glb')
